# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'franklin-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for franklin-demo
  pod "LeanCloud"
  pod "RealmSwift"

  target 'franklin-demoTests' do
    inherit! :search_paths
    # Pods for testing
    pod "LeanCloud"
    pod "RealmSwift"
  end

  target 'franklin-demoUITests' do
    # Pods for testing
    pod "LeanCloud"
    pod "RealmSwift"
  end

end
